language: ruby
rvm:
  - 2.2.3
notifications:
  slack: hacken-in:v0VPwCbdNxNY7oVfJGsFLAJS
bundler_args: --without development
before_script:
  - psql -c 'create database hcking_test;' -U postgres
  - "cp config/database.yml_travis config/database.yml"
script: "bundle exec rake db:drop db:create db:migrate ci"
sudo: false
cache: bundler
addons:
  postgresql: "9.3"
  code_climate:
    repo_token: e9119a0532e351ecb5e7a0807c08b3dcd5771bc31f85b45f823f1dbcd22f78fb
after_success:
  - openssl aes-256-cbc -K $encrypted_ece5f7dc116b_key -iv $encrypted_ece5f7dc116b_iv -in config/travis/travis-deploy-key.enc -out config/travis/travis-deploy-key -d
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 config/travis/travis-deploy-key # this key should have push access
  - ssh-add config/travis/travis-deploy-key
  - ssh-add -l
  - '[[ "$TRAVIS_BRANCH" == "back-to-uberspace" ]] && bundle exec cap master deploy'
