language: ruby
rvm:
  - 2.0.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
notifications:
  slack: hacken-in:v0VPwCbdNxNY7oVfJGsFLAJS
bundler_args: --without development
before_script:
  - psql -c 'create database hcking_test;' -U postgres
  - "cp config/database.yml_travis config/database.yml"
  - "cp config/twitter.yml_example config/twitter.yml"
  - "cp config/initializers/devise.rb_example config/initializers/devise.rb"
script: "bundle exec rake db:drop db:create db:migrate ci"
cache: bundler
