version: '3'
services:
  web:
    image: hackenin/hacken-in:latest
    build:
      context: .
    command: bundle exec puma -C config/puma.rb
    environment:
      RAILS_ENV: "development"
      DATABASE_URL: 'postgres://postgres:@db:5432'
    env_file: .env
    volumes:
      - ".:/app"
      - "bundle:/bundle"
    user: "${USER_MAPPING:-1000:1000}"
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: postgres
    volumes:
    - postgres:/var/lib/postgresql/data

volumes:
  bundle:
  postgres:
